server:
  port: 8083

spring:
  application:
    name: order-service-api

  datasource:
    url: jdbc:mysql://localhost:3306/order_service-api-DB?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#
#  instance:
#    prefer-ip-address: true